services:
#    tns_upload.example:
#        class: TNS\UploadBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    upload.annotation_reader:
        class: TNS\UploadBundle\Annotation\UploadAnnotationReader
        arguments: ["@annotations.reader"]

    upload.handler:
        class: TNS\UploadBundle\Handler\UploadHandler


    upload.subscriber:
        class: TNS\UploadBundle\Listener\UploadSubscriber
        arguments: ["@upload.annotation_reader", "@upload.handler"]
        tags:
            - { name: doctrine.event_subscriber, connection: default }